version: "3.8"
services:
  scylla-node1:
    image: scylladb/scylla:6.1.1
    container_name: result-node1
    networks:
      - scylla-net
    ports:
      - "9042:9042"
    command: --overprovisioned 1 --smp 1
    volumes:
      - result-node1-data:/var/lib/scylla

  scylla-node2:
    image: scylladb/scylla:6.1.1
    container_name: result-node2
    networks:
      - scylla-net
    command: --overprovisioned 1 --smp 1 --seeds="result-node1"
    volumes:
      - result-node2-data:/var/lib/scylla

  scylla-node3:
    image: scylladb/scylla:6.1.1
    container_name: result-node3
    networks:
      - scylla-net
    command: --overprovisioned 1 --smp 1 --seeds="result-node1"
    volumes:
      - result-node3-data:/var/lib/scylla

networks:
  scylla-net:

volumes:
  result-node1-data:
  result-node2-data:
  result-node3-data:
